---
tags:
  microscopes: https://store.publiclab.org/products/microscope
  microscope: https://store.publiclab.org/products/microscope
  infragram: https://store.publiclab.org/products/infragram-diy-filter-pack
  baby-legs: https://store.publiclab.org/products/babylegs
  infragram-pi: https://store.publiclab.org/products/infragram-pi-camera
  infragram: https://store.publiclab.org/products/infragram-diy-filter-pack
  simple-air-sensor: https://store.publiclab.org/products/simple-air-sensor
  pi-camera: https://store.publiclab.org/products/raspberry-pi-camera
  spectrometer: https://store.publiclab.org/products/lego-spectrometer-kit